# 0. Імпортувати numpy загальноприйнятим способом.

In [4]:
import numpy as np 


 # 0. Імпортувати бібліотеку pandas.

In [5]:
import pandas as pd



# 1.Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [6]:
grades = [88, 92, 85, 91, 75]
grades_array = np.array(grades)

# 2.Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт
# (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно.
#Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [7]:
products = [
    [25.5, 7.5, 22.0, 45.2],  #Ціни в першому магазині
    [26.0, 8.0, 21.5, 44.5],  #Ціни в другому магазині
    [25.0, 7.0, 22.5, 46.0]   #Ціни в третьому магазині
]
product_matrix = np.array(products)

# 3 Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [8]:
print("Тип даних масиву grades_array:", grades_array.dtype)
print("Тип даних матриці product_matrix:", product_matrix.dtype)

Тип даних масиву grades_array: int64
Тип даних матриці product_matrix: float64


# 4Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [ ]:
print("Форма масиву grades_array:", grades_array.shape)
print("Форма матриці product_matrix:", product_matrix.shape)

In [ ]:
# 5.Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого
# (з рівними проміжками) прибутку з продажів за тиждень, де у перший день не було продажів, а в останній день тижня
# вдалося заробити 1000 грн 50 коп.

In [9]:
weekly_profits = np.linspace(0, 1000.50, 7)
print("динаміка прибутку за тиждень:", weekly_profits)

динаміка прибутку за тиждень: [   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]


# 6.Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [10]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
vertical_concat = np.vstack((array1, array2))
horizontal_concat = np.hstack((array1, array2))
print("вертикальне об'єднння:\\n", vertical_concat)
print("щоризонтальне об'єднання:\\n", horizontal_concat)

вертикальне об'єднння:\n [[1 2 3]
 [4 5 6]]
щоризонтальне об'єднання:\n [1 2 3 4 5 6]


# 7.Визначити функцію, яка приймає на вході масив і транспонує його.

In [11]:
def transpose_array(array):
    return array.T

transposed = transpose_array(product_matrix)
print("Транспонована матриця:", transposed)

Транспонована матриця: [[25.5 26.  25. ]
 [ 7.5  8.   7. ]
 [22.  21.5 22.5]
 [45.2 44.5 46. ]]


# 8. Створіть два масиви. Використовуючи ці масиви, продемонструйте:

In [12]:
array3 = np.array([1, 2, 3])
array4 = np.array([4, 5, 6])

# 1) операцію по-елементного додавання

In [13]:
element_addition = array3 + array4

# 2)операцію по-елементного віднімання

In [14]:
element_subtraction = array3 - array4

# 3)множення масиву на число

In [15]:
array_scalar_multiplication = array3 * 2

# 4)операцію по-елементного множення

In [16]:
element_multiplication = array3 * array4

# 5)матричного множення

In [17]:
matrix_multiplication = np.dot(array3.reshape(-1, 1), array4.reshape(1, -1))
print("По-елементне додавання:", element_addition)
print("По-елементне віднімання:", element_subtraction)
print("Множення масиву на число:", array_scalar_multiplication)
print("По-елементне множення:", element_multiplication)
print("Матричне множення:", matrix_multiplication)

По-елементне додавання: [5 7 9]
По-елементне віднімання: [-3 -3 -3]
Множення масиву на число: [2 4 6]
По-елементне множення: [ 4 10 18]
Матричне множення: [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


# 9.Створіть двовимірний масив (матрицю) та розрахуйте:

In [18]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 1) мінімальне число

In [19]:
min_value = np.min(matrix)

# 2) максимальне число

In [20]:
max_value = np.max(matrix)

# 3) суму чисел

In [21]:
sum_values = np.sum(matrix)

# 4) мінімальні числа для кожного рядка

In [22]:
min_row_values = np.min(matrix, axis=1)

# 5) максимальні числа для кожного стовпчика

In [23]:
max_column_values = np.max(matrix, axis=0)
print("Мінімальне число:", min_value)
print("Максимальне число:", max_value)
print("Сума чисел:", sum_values)
print("Мінімальні числа для кожного рядка:", min_row_values)
print("Максимальні числа для кожного стовпчика:", max_column_values)

Мінімальне число: 1
Максимальне число: 9
Сума чисел: 45
Мінімальні числа для кожного рядка: [1 4 7]
Максимальні числа для кожного стовпчика: [7 8 9]


# 10. Створіть матрицю, де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

In [24]:
repeated_matrix = np.array([[1, 2, 2], [2, 3, 3], [3, 3, 4]])
unique_values, counts = np.unique(repeated_matrix, return_counts=True)
print("Унікальні значення:", unique_values)
print("Частоти значень:", counts)

Унікальні значення: [1 2 3 4]
Частоти значень: [1 3 4 1]


# II. Importing. Creating DF            Винесла на початок !!!!
# 11.Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим.

In [25]:
data = {
    'Прізвище': ['Рибак', 'Рибак', 'Рибак'],
    'Ім\'я': ['Людмила', 'Людмила', 'Людмила'],
    'Дата народження': ['2006-06-08', '2006-06-08', '2006-06-08'],
    'Маса тіла': [54, 50, None],  # None для відсутніх даних
    'Медичне страхування': [True, False, True]
}
df = pd.DataFrame(data)
print(df)

df = pd.DataFrame(data)
print(df)


  Прізвище     Ім'я Дата народження  Маса тіла  Медичне страхування
0    Рибак  Людмила      2006-06-08       54.0                 True
1    Рибак  Людмила      2006-06-08       50.0                False
2    Рибак  Людмила      2006-06-08        NaN                 True
  Прізвище     Ім'я Дата народження  Маса тіла  Медичне страхування
0    Рибак  Людмила      2006-06-08       54.0                 True
1    Рибак  Людмила      2006-06-08       50.0                False
2    Рибак  Людмила      2006-06-08        NaN                 True


# III. Reading from file
#12.Завантажити файл missile_attacks_daily.csv з [Kaggle](https:
#//www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv).
#Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі).
#Зчитати датафрейм з файлу та вивести датафрейм на екран.
#Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

In [27]:
path_to_missiles = 'archive/missile_attacks_daily.csv'
path_to_uav = 'archive/missiles_and_uav.csv'
#зчитування з файлів
df_missile_attacks = pd.read_csv(path_to_missiles)
df_missiles_and_uav = pd.read_csv(path_to_uav)

In [28]:
#вивід у консоль
print("Информация о missile_attacks_daily.csv:")
print(df_missile_attacks.info())
print("\nПервые строки данных missile_attacks_daily.csv:")
print(df_missile_attacks.head())

print("\nИнформация о missiles_and_uav.csv:")
print(df_missiles_and_uav.info())
print("\nПервые строки данных missiles_and_uav.csv:")
print(df_missiles_and_uav.head())


Информация о missile_attacks_daily.csv:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2079 entries, 0 to 2078
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   time_start            2079 non-null   object 
 1   time_end              2079 non-null   object 
 2   model                 2079 non-null   object 
 3   launch_place          1050 non-null   object 
 4   target                2051 non-null   object 
 5   carrier               227 non-null    object 
 6   launched              2076 non-null   float64
 7   destroyed             2075 non-null   float64
 8   not_reach_goal        172 non-null    float64
 9   cross_border_belarus  33 non-null     float64
 10  back_russia           35 non-null     float64
 11  still_attacking       31 non-null     float64
 12  affected region       8 non-null      object 
 13  destroyed_details     309 non-null    object 
 14  launched_details      4 non-null

# IV. Data understanding
# 13 Виведіть на екран перші 10 рядків зчитаного датафрейму.

In [29]:
print(df_missile_attacks.head(10))

         time_start          time_end           model  \
0  2025-02-02 19:00  2025-02-03 09:00  Shahed-136/131   
1  2025-02-01 21:00  2025-02-02 09:00  Shahed-136/131   
2        2025-02-02        2025-02-02          Молнія   
3        2025-02-02        2025-02-02            ZALA   
4        2025-02-02        2025-02-02        Supercam   
5        2025-02-02        2025-02-02          Lancet   
6  2025-01-31 19:00  2025-02-01 09:00       X-59/X-69   
7  2025-01-31 19:00  2025-02-01 09:00           X-31P   
8  2025-01-31 19:00  2025-02-01 09:00       X-22/X-32   
9  2025-01-31 19:00  2025-02-01 09:00     X-101/X-555   

                                        launch_place   target  carrier  \
0  Primorsko-Akhtarsk and Chauda, Crimea and Kurs...  Ukraine      NaN   
1  Primorsko-Akhtarsk and Kursk oblast and Oryol ...  Ukraine      NaN   
2                                                NaN    south      NaN   
3                                                NaN    south      NaN   
4 

# 14.Отримайте інформацію про форму датафрейму.

In [30]:
print(df_missile_attacks.shape)

(2079, 17)


# 15.Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

In [31]:
print(df_missile_attacks.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2079 entries, 0 to 2078
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   time_start            2079 non-null   object 
 1   time_end              2079 non-null   object 
 2   model                 2079 non-null   object 
 3   launch_place          1050 non-null   object 
 4   target                2051 non-null   object 
 5   carrier               227 non-null    object 
 6   launched              2076 non-null   float64
 7   destroyed             2075 non-null   float64
 8   not_reach_goal        172 non-null    float64
 9   cross_border_belarus  33 non-null     float64
 10  back_russia           35 non-null     float64
 11  still_attacking       31 non-null     float64
 12  affected region       8 non-null      object 
 13  destroyed_details     309 non-null    object 
 14  launched_details      4 non-null      object 
 15  launch_place_details 

# 16.Отримайте статистику для колонок числового типу.

In [32]:
print(df_missile_attacks.describe())

          launched    destroyed  not_reach_goal  cross_border_belarus  \
count  2076.000000  2075.000000      172.000000             33.000000   
mean     11.114644     7.769639       21.720930              2.303030   
std      22.047798    14.678258       19.729546              2.023068   
min       1.000000     0.000000        1.000000              1.000000   
25%       1.000000     1.000000        4.750000              1.000000   
50%       2.000000     1.000000       17.500000              2.000000   
75%       9.000000     7.000000       31.000000              2.000000   
max     193.000000    99.000000      105.000000             10.000000   

       back_russia  still_attacking  
count    35.000000        31.000000  
mean      2.000000         2.709677  
std       1.137593         2.818907  
min       1.000000         1.000000  
25%       1.000000         1.000000  
50%       2.000000         1.000000  
75%       3.000000         3.500000  
max       5.000000        10.000000  


# 17.Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці,
# яка має найменше унікальних значень.

In [33]:
unique_counts = df_missile_attacks.nunique()
print(unique_counts)
min_unique_col = unique_counts.idxmin()
print("Колонка з найменшою кількістю унікальних значень:", min_unique_col)
print(df_missile_attacks[min_unique_col].value_counts())

time_start               885
time_end                1038
model                     61
launch_place             141
target                    99
carrier                   58
launched                 120
destroyed                 83
not_reach_goal            58
cross_border_belarus       7
back_russia                5
still_attacking            8
affected region            8
destroyed_details        305
launched_details           4
launch_place_details       4
source                   980
dtype: int64
Колонка з найменшою кількістю унікальних значень: launched_details
launched_details
{'X-101/X-555': 50, 'Kalibr': 12}                     1
{'X-101/X-555': 55, 'Kalibr': 24, 'Iskander-K': 7}    1
{'X-101/X-555': 57, 'Kalibr': 28}                     1
{'X-101/X-555': 77, 'Kalibr': 28, 'X-59/X-69': 10}    1
Name: count, dtype: int64


# V. Data Cleaning
# 19.Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

In [34]:
df_missile_attacks['launched'] = df_missile_attacks['launched'].astype('Int64')
print(df_missile_attacks['launched'].dtype)

Int64


# 20.Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

In [35]:
threshold = len(df_missile_attacks) * 0.3
df_missile_attacks.dropna(thresh=threshold, axis=1, inplace=True)

# 21.Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо).
# Не забудьте оновити індекс.

In [36]:
df_missile_attacks = df_missile_attacks[df_missile_attacks['launched'] > 0].drop_duplicates().reset_index(drop=True)

#22.Виведіть на екран всі рядки, де є хоч одне пропущене значення.

In [37]:
print(df_missile_attacks[df_missile_attacks.isnull().any(axis=1)])

            time_start          time_end               model     launch_place  \
2           2025-02-02        2025-02-02              Молнія              NaN   
3           2025-02-02        2025-02-02                ZALA              NaN   
4           2025-02-02        2025-02-02            Supercam              NaN   
5           2025-02-02        2025-02-02              Lancet              NaN   
6     2025-01-31 19:00  2025-02-01 09:00           X-59/X-69  Voronezh oblast   
...                ...               ...                 ...              ...   
2071  2022-10-01 12:00  2022-10-01 12:00            Orlan-10              NaN   
2072        2022-09-30        2022-09-30            Orlan-10              NaN   
2073  2022-09-29 23:00  2022-09-29 23:59      Shahed-136/131              NaN   
2074        2022-09-28        2022-09-28                X-59              NaN   
2075        2022-09-28        2022-09-28  Reconnaissance UAV              NaN   

                           